### PR TITLE
Relocate netcdf iteration code

### PR DESCRIPTION
**Pull request by jonescc**
Copy classes supporting iteration over netcdf variables out of talend components project to a separate repository that can be built and included in geoserver-build as well for generating csv timeseries files

### CODE REVIEW

**Comment by julian1** [comment]
This is just the stuff already in production right?

**Comment by jonescc** [comment]
Yes.  Would like to get the code merged as is and then make changes.

**Comment by julian1** [comment]
I would like to merge this but, it says,

```
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.
```

**Comment by jonescc** [comment]
Fixed

**Pull request merged**
